org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.paths=E:/Coding/Minecraft/tools/jdk-25.0.3+9

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.12
modmenu_version=21.0.0
modmenu_jar=../tools/deps/modmenu-21.0.0.jar

fabric_networking_api_version=6.3.8+fcdff87f5d
fabric_lifecycle_events_version=4.1.9+ffef5f675d
fabric_key_mapping_api_version=2.0.8+3434d6d95d

mod_version=1.0.5
maven_group=org.lts
archives_base_name=tab-name-dimmer
